import Head from 'next/head'
import styles from '../styles/Home.module.css'
import zengo from '../zengo.json'
 

export default function Home() {
  function kotoba() {
    const month = new Date().getMonth()
    if(month === 0){
      return "January"
    }else if (month === 1) {
      return "Feburary"
    } else if (month === 2) {
      return "March"
    } else if(month === 3) {
      return "April"
    } else if (month === 4) {
      return "May"
    } else if (month === 5) {
      return "June"
    } else if (month === 6) {
      return "July"
    } else if (month === 7) {
      return "August"
    } else if (month === 8) {
      return "September"
    } else if (month === 9) {
      return "October"
    }else if (month === 10) {
      return "November"
    } else {
      return "December"
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Zengo of the Month</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div className={styles.body}>
      <h1 className={styles.title}>Zengo of the Month</h1>
        <h1 className={styles.month}>{kotoba()}</h1>
      <main className={styles.main}>
      
        <div className={styles.card}>
          {zengo.map(zen =>  {
            return(
              <ul key={zen.id} className={styles.card}>
                <img className={styles.image} src={zen.image} alt={zen.name} />
                <li className={styles.poem}>{zen.poem}</li>
                <li>{zen.description}</li>
              </ul>
            )
          })}
        </div>
      </main>

      <footer className={styles.footer}>
       <h4 className={styles.footer}>Ai Krasner</h4>
      </footer>
    </div>
    </div>
  )
}
